name: Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run GoReleaser via Docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run --rm --privileged \
            -v $PWD:/repo \
            -w /repo \
            -e GITHUB_TOKEN \
            goreleaser/goreleaser release
